name: Apigateway (CI)
on:
  push:
    branches: ['develop']
    paths: ['apigateway/**']
jobs:
  build:
    runs-on: ubuntu-latest
    #env:
    #  working-directory: ./apigateway
    #defaults:
    #  run:
    #    working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: ./apigateway/npm install
      - run: ./apigateway/npm ci
      - run: ./apigateway/npm run build --if-present
